settings:
  title: 'LQ 相关服务状态'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有服务全部正常'
  notAllmonitorsOperational: '部分服务正常'
  monitorLabelOperational: '运作中'
  monitorLabelNotOperational: '非运作中'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '无事件'
  dayInHistogramNotOperational: '个事件'
  
monitors:
  - id: lq-faka
    name: LQ 店铺
    description: 'LQ 发卡店铺，自主购买各种AI账号，可零售，可批发，全网低价'
    url: 'https://fk.lqqq.ltd/'
    method: GET
    expectStatus: 200
    followRedirect: false #
    linkable: true #

  - id: lq-api
    name: LQ 中转 API
    description: 'LQ 中转 API ，可用GPT4、Claude3、Dalle3'
    url: 'https://api.lqqq.ltd/'
    method: GET
    expectStatus: 200
    followRedirect: false #
    linkable: true #
